// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ATMBQpDCSsuwWtQ9gb7XU7c7QGot0gc',
    appId: '1:412044710378:web:f19457feb7206f6ab0a293',
    messagingSenderId: '412044710378',
    projectId: 'crud-c49',
    authDomain: 'crud-c49.firebaseapp.com',
    storageBucket: 'crud-c49.firebasestorage.app',
    measurementId: 'G-P8HJBLZR8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt8xGeOt0j-X1I3xxiHAzSsCXo1gRkTq4',
    appId: '1:412044710378:android:613630efe0c63a69b0a293',
    messagingSenderId: '412044710378',
    projectId: 'crud-c49',
    storageBucket: 'crud-c49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXR_zukM0xaS5zF6cOu35Mi7vBF91vCs',
    appId: '1:412044710378:ios:9ec98ddf9f63e65fb0a293',
    messagingSenderId: '412044710378',
    projectId: 'crud-c49',
    storageBucket: 'crud-c49.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXR_zukM0xaS5zF6cOu35Mi7vBF91vCs',
    appId: '1:412044710378:ios:9ec98ddf9f63e65fb0a293',
    messagingSenderId: '412044710378',
    projectId: 'crud-c49',
    storageBucket: 'crud-c49.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ATMBQpDCSsuwWtQ9gb7XU7c7QGot0gc',
    appId: '1:412044710378:web:c5dfbd1c9f4b7492b0a293',
    messagingSenderId: '412044710378',
    projectId: 'crud-c49',
    authDomain: 'crud-c49.firebaseapp.com',
    storageBucket: 'crud-c49.firebasestorage.app',
    measurementId: 'G-9HBKKG997C',
  );

}